name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify Build Output
        run: |
          echo "Checking build output structure:"
          ls -R dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET }}
          aws-region: us-west-2

      - name: Deploy to S3
        run: |
          # First ensure the assets directory exists
          if [ ! -d "dist/assets" ]; then
            echo "Creating assets directory"
            mkdir -p dist/assets
          fi

          # Deploy index.html with no cache
          aws s3 cp dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache, no-store, must-revalidate"

          # Deploy assets with long cache
          aws s3 sync dist/assets/ s3://${{ secrets.S3_BUCKET }}/assets \
            --delete \
            --cache-control "max-age=31536000, public"
